feat(#70): :technologist: add rootdir '@' in back end and factor imports
iurynogueira/myreef pull request #71
Opened 2022-05-18 15:29 UTC by isaqueveras

2022-05-18 15:36 UTC, iurynogueira requested changes
Update branch and run tests, this is a big refactor.

2022-05-18 15:36 UTC, iurynogueira commented on back/tsconfig.json
>  }
add whiteline

2022-05-19 14:18 UTC, isaqueveras commented
what is missing for this PR to be merged?

2022-05-23 13:27 UTC, iurynogueira approved these changes

2022-05-23 13:27 UTC, merged